app/routes.php
<?php

Route::get('facebook', [ 'as' => 'facebook', function() { return Redirect::to('https://www.facebook.com/pages/Pelugion/1428073117412979'); }]);
Route::get('twitter', [ 'as' => 'twitter', function() { return Redirect::to('https://www.twitter.com/pelugion'); }]);

// Route::get('/', function() {return View::make('temp'); });

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::get('news/{id}/{slug?}', ['as' => 'news.show', 'uses' => 'NewsController@show']);

Route::get('about', ['as' => 'about.index', 'uses' => 'AboutController@index']);
Route::get('about/{id}/{slug}', [
	'uses' => 'AboutController@showUser',
	'as' => 'about.user'
]);

Route::get('contact', ['as' => 'contact.index', 'uses' => 'ContactController@index']);
Route::post('contact', ['as' => 'contact.send', 'uses' => 'ContactController@send']);

Route::get('gigs', [ 'as' => 'gigs.index', 'uses' => 'GigController@index' ]);
Route::get('gigs/{id}/{slug?}', [ 'as' => 'gigs.show', 'uses' => 'GigController@show']);

Route::get('music', [ 'as' => 'music.index', 'uses' => 'MusicController@index' ]);
Route::get('media', [ 'as' => 'media.index', 'uses' => 'MediaController@index' ]);


Route::group(array('prefix' => 'admin'), function() {

	Route::get('users/switch-back', ['before' => 'auth', 'uses' => 'AdminUserController@switchBack']);

	Route::group(array('before' => 'auth'), function() {
		Route::resource('users', 'AdminUserController');
		Route::post('users/{id}/updateSpecific', 'AdminUserController@updateSpecific');
		Route::get('users/switch/{id}', 'AdminUserController@switchUser');
		Route::get('log', 'AdminLogController@index');
		Route::get('news/delete-all', [ 'as' => 'admin.news.delete-all', 'uses' => 'AdminNewsController@deleteAll']);
	});
	
	Route::get('/', function() {
		if(!Auth::check()) {
			return Redirect::to('admin/login');
		} else {
			return Redirect::route('dash');
		}
	});


	Route::group(array('before' => 'auth'), function() {
		Route::get('dash', array('uses' => 'AdminDashController@index', 'as' => 'dash'));
		Route::post('account', ['before' => 'csrf', 'uses' => 'AdminAccountController@update']);
		Route::post('account/profile', ['before' => 'csrf', 'uses' => 'AdminAccountController@updateProfile']);
		Route::post('account/profile-image', ['before' => 'csrf', 'uses' => 'AdminAccountController@updateProfileImage']);
		Route::post('account/change-password', ['before' => 'csrf', 'uses' => 'AdminAccountController@updatePassword']);
		Route::get('account/remove-avatar', 'AdminAccountController@removeAvatar');
		Route::get('account', 'AdminAccountController@index');
		
		Route::get('logout', array('as' => 'logout', 'uses' => 'AdminLoginController@logout'));

		Route::resource('news', 'AdminNewsController');
		Route::get('news/{id}/publish', [
			'uses' => 'AdminNewsController@publish',
			'as' => 'admin.news.publish'
		]);
		Route::get('news/{id}/unpublish', [
			'uses' => 'AdminNewsController@unpublish',
			'as' => 'admin.news.unpublish'
		]);
		Route::get('news/{id}/delete', [
			'uses' => 'AdminNewsController@delete',
			'as' => 'admin.news.delete'
		]);

		Route::resource('content', 'AdminContentController');
		Route::post('content/update-section', 'AdminContentController@updateSection');

		Route::resource('gigs', 'AdminGigController');
		Route::post('gigs/{id}/update-image', [ 'as' => 'admin.gigs.update-image', 'before' => 'csrf', 'uses' => 'AdminGigController@updateImage']);

		Route::post('gigs/create/2', [
			'as' => 'admin.gigs.create.step-two',
			'uses' => 'AdminGigController@stepTwo'
		]);
		Route::get('gigs/create/2', 'AdminGigController@stepTwo');

		Route::post('gigs/create/3', [
			'as' => 'admin.gigs.create.step-three',
			'uses' => 'AdminGigController@stepThree'
		]);

		Route::get('gigs/create/3', 'AdminGigController@stepThree');

		Route::get('gigs/create/{wildcard}', [
			'as' => 'admin.gigs.reset-form',
			'uses' => 'AdminGigController@resetAndRedirect'
		]);

		Route::group([ 'prefix' => 'ajax' ], function() {
			Route::get('venues', 'AdminAjaxController@getAllVenues');
			Route::post('gigs/{id}/venue', 'AdminGigController@updateVenue');
		});
	});

	Route::group(array('before' => 'guest'), function() {
		Route::get('login/password-reset/{token}', 'AdminLoginController@resetPassword');
		Route::get('login/forgotten', 'AdminLoginController@displayForgotten');
		Route::post('login/forgotten', 'AdminLoginController@submitForgotten');
		Route::resource('login', 'AdminLoginController', array('only' => array('index', 'store')));
	});

});

app/models/LogItem.php
<?php

	class LogItem extends BaseModel {

		public $table = 'log';

		public function object() {
			return $this->morphTo();
		}

		public function getData() {
			return json_decode($this->data);
		}

		public function getDescriptionAttribute() {
			switch($this->type) {
				case 'user.login':
					return '<span data-field="full_name">'.$this->object->full_name . '</span> logged in';
					break;

				case 'user.failed-login':
					return '<span data-field="full_name">'.$this->object->full_name . '</span> performed a failed login attempt';
					break;

				case 'user.logout':
					return '<span data-field="full_name">'.$this->object->full_name . '</span> logged out';
					break;

				case 'user.update-account':
					return '<span data-field="full_name">'.$this->object->full_name . '</span> updated their account';
					break;

				case 'user.update-password':
					return '<span data-field="full_name">'.$this->object->full_name . '</span> updated their password';
					break;

				case 'user.update-avatar':
					return '<span data-field="full_name">'.$this->object->full_name . '</span> updated their avatar';
					break;

				case 'user.update-profile':
					return '<span data-field="full_name">'.$this->object->full_name . '</span> updated their profile';
					break;

				case 'user.switch-account':
					$data = $this->getData();
					$u = User::find((int) $data->id);
					if(!$u) { $this->delete(); return false; }
					return '<span data-field="full_name">'.$this->object->full_name . '</span> switched account to <a href="' . url('admin/users/'.$u->id) . '">' . $u->full_name . '</a>';
					break;

				case 'user.switch-back':
					return '<span data-field="full_name">'.$this->object->full_name . '</span> switched back to their own account';
					break;

				case 'user.request-password-reset':
					return '<span data-field="full_name">'.$this->object->full_name . '</span> requested a password reset';
					break;

				case 'user.update-other-account':
					$data = $this->getData();
					$u = User::find((int) $data->id);
					if(!$u) { $this->delete(); return false; }
					return '<span data-field="full_name">'.$this->object->full_name . '</span> updated account <a href="' . url('admin/users/'.$u->id) . '">' . $u->full_name . '</a>';
					break;

				case 'user.reset-password': 
					return '<span data-field="full_name">'.$this->object->full_name . '</span> reset their password';
					break;

				case 'news.publish':
					$data = $this->getData();
					$p = News::withTrashed()->find((int) $data->id);
					if(!$p) { $this->delete(); return false; }
					return '<span data-field="full_name">'.$this->object->full_name .'</span> published news post <a href="' . route('admin.news.show', $p->id) . '">'.$p->title.'</a>';
					break;

				case 'news.unpublish':
					$data = $this->getData();
					$p = News::withTrashed()->find((int) $data->id);
					if(!$p) { $this->delete(); return false; }
					return '<span data-field="full_name">'.$this->object->full_name .'</span> unpublished news post <a href="' . route('admin.news.show', $p->id) . '">'.$p->title.'</a>';
					break;

				case 'news.post':
					$data = $this->getData();
					$p = News::withTrashed()->find((int) $data->id);
					if(!$p) { $this->delete();  return false; }
					return '<span data-field="full_name">'.$this->object->full_name .'</span> posted news post <a href="' . route('admin.news.show', $p->id) . '">'.$p->title.'</a>';
					break;

				case 'gig.create':
					$data = $this->getData();
					$gig = Gig::withTrashed()->find((int) $data->id);
					if(!$gig) { $this->delete(); return false; }
					return '<span data-field="full_name">'.$this->object->full_name .'</span> created gig <a href="' . route('admin.gigs.edit', $gig->id) . '">'.$gig->name.'</a>';
					break;

				default:
					return;
					break;

			}
		}
	}

app/models/User.php
<?php

use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableInterface;
use Pelugion\Interfaces\DisplayPhotoInterface;

class User extends BaseModel implements UserInterface, RemindableInterface, DisplayPhotoInterface {

	protected $table = 'users';
	public $fillable = ['first_name', 'last_name', 'email', 'password', 'date_of_birth', 'role', 'band_member', 'created_at', 'updated_at'];
	public $dates = ['created_at','updated_at','deleted_at','date_of_birth'];

	/**
	 * Get the unique identifier for the user.
	 *
	 * @return mixed
	 */
	public function getAuthIdentifier()
	{
		return $this->getKey();
	}

	/**
	 * Get the password for the user.
	 *
	 * @return string
	 */
	public function getAuthPassword()
	{
		return $this->password;
	}

	/**
	 * Get the e-mail address where password reminders are sent.
	 *
	 * @return string
	 */
	public function getReminderEmail()
	{
		return $this->email;
	}

	public function isSuperAdmin() {
		return $this->role == 1;
	}

	public function instruments() {
		return $this->belongsToMany('Instrument', 'instrument_user');
	}

	public function getFullNameAttribute() {
		return $this->first_name . " " . $this->last_name;
	}


	public function resetToken() {
		return $this->hasOne('ResetToken');
	}

	public function alerts() {
		return $this->hasMany('Alert');
	}

	public function notices() {
		return $this->hasMany('Notice');
	}

	public function news() {
		return $this->hasMany('News', 'author_id');
	}

	public function hasAccessTo($object) {
		if($this->isSuperAdmin()) return true;

		switch(get_class($object)) {
			case "News":
				if($object->author_id == $this->id) return true;
				break;

			default:
				if($this->isSuperAdmin()) return true;
				return false;
		}
	}

	public function isBandMember() {
		if($this->band_member == 0) return false;
		return true;
	}

	public function getNameSlug() {
		return Str::slug($this->full_name);
	}

	public function getSlugAttribute() {
		return $this->getNameSlug();
	}

	public function scopeBandMembers($query) {
		return $query->where('band_member', '1');
	}

	public function getInstrumentsList() {
		if($this->instruments->count() == 0) return 'No Instruments';

		$list = '';

		$i = 1;
		foreach($this->instruments as $instrument) {
			$list.= $instrument->name;

			if($i != $this->instruments->count()) $list .= ' / ';

			$i++;
		}

		return $list;
	}

	public function generateAboutUrl() {
		if(!$this->isBandMember()) return false;

		return route("about.user", [ $this->id, Str::slug($this->full_name) ]);
	}

	public function photos() {
		return $this->morphToMany('Photo');
	}  

	/**
     * Says if the object has a photo in the database
     * @return boolean Whether or not they have a photo
     */
    public function hasPhoto() {
        return $this->avatar_url != null;
    }

    /**
     * Get the URL of the photo
     * @return String URL of the photo (or placeholder)
     */
    public function getPhotoUrl() {
        if($this->avatar_url) {
            return asset(Config::get('app.image_display_path').$this->avatar_url);
        } else {
            return Config::get('app.placeholder_path');
        }
    }

    public function getPhotoPath() {
    	return ($this->avatar_url) ? $this->avatar_url : Config::get('app.placeholder_path');
    }

}

app/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('content')

	<h1 class='page-title'>Edit User: {{ $user->full_name }}</h1>
	
	<div class='panel'>
	{{ Form::open(array('url' => 'admin/users/'.$user->id, 'method' => 'PUT', 'class' => 'form-horizontal'))}}

		<div class='small-12'>
		<label for='first_name'>First Name <span class='redtext'>*</span></label>
		<input type='text' class='form-control' name='first_name' placeholder='First Name' value='{{ $user->first_name }}' />
		</div>

		<div class='small-12'>
		<label for='last_name'>Last Name <span class='redtext'>*</span></label>
		<input type='text' class='form-control' name='last_name' placeholder='Last Name' value='{{ $user->last_name }}' />
		</div>

		<div class='small-12'>
		<label for='email'>Email Address <span class='redtext'>*</span></label>
		<input type='email' class='form-control' name='email' placeholder='Email' value='{{ $user->email }}' />
		</div>

		<div class='small-12'>
		<label for='email'>Is this user a band member? </label>
		<input type='checkbox' class='form-control' name='band_member' 
			@if($user->band_member == 1)
				checked
			@endif
		/>
		</div>

		<div class='small-12'>
		<label for='instruments'>Which instruments do you play? <span class='redtext'>*</span></label>
		@foreach($instruments as $instrument)
			<input type='checkbox' name='instruments[{{ $instrument->id }}]'
			@if(in_array($instrument->id, $instruments_list))
				checked
			@endif
			/> {{ $instrument->name }}<br />
		@endforeach
		</div>

		<div class='small-12'>
		<label for='role'>Role <span class='redtext'>*</span></label>
		<select class='form-control' name='role'>
			<option value='0' @if(!$user->isSuperAdmin()) selected @endif>Admininstrator</option>
			<option valud='1' @if($user->isSuperAdmin()) selected @endif>Super Administrator</option>
		</select>
		</div>

		<div class='small-12'>
		<label for='password'>New Password</label>
		<input type='password' class='form-control' name='password'  />
		</div>

		<div class='small-12'>
		<label for='password_confirm'>New Password (repeat)</label>
		<input type='password' class='form-control' name='password_confirm'  />
		</div>

		<button type="submit" class="btn btn-default"><i class="icon-check-sign"></i> Update Account</button>

		</div>
	</form>

@endsection

app/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('content')

	<h1 class='page-title'>Manage Users</h1>

	<table class="small-12">
		<thead>
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>Created</th>
				<th>Updated</th>
			</tr>
		</thead>
		<tbody>
			@foreach($users as $user)
				<tr class='clickable' href='{{ url("admin/users/".$user->id) }}'>
					<td>{{ $user->full_name }}</td>
					<td>{{ $user->email }}</td>
					<td>{{ Time::createFromTimestamp(strtotime($user->created_at))->diffForHumans() }}</td>
					<td>
						@if($user->updated_at != $user->created_at)
							{{ Time::createFromTimestamp(strtotime($user->updated_at))->diffForHumans() }}
						@else
							N/A
						@endif
					</td>
				</tr>
			@endforeach
		</tbody>
	</table>

@stop

app/views/admin/users/show.blade.php
@extends('layouts.admin')

@section('content')	
	<a href='{{ URL::to('admin/users') }}' class='button small'><i class='icon-chevron-sign-left'></i> Go Back</a>
	<h1 class='page-title'><span data-field="full_name">{{$user->full_name}}</span></h1>
	<div class='panel block-grid small-12 edit-tools align-center'>
		<p><a class='button tiny small-12 medium-3
		@if($user->id == Auth::user()->id)
			disabled' disabled href='#'
		@else
			' href='{{ url("admin/users/switch/".$user->id) }}'
		@endif
		 >Switch to User</a>

		 <a href="{{ url('admin/users/'.$user->id.'/edit') }}" data-hint='Edit User' class="button tiny small-12 medium-3 hint--right hint--rounded">Edit User</a>
	</div>

	<div class="small-12 large-4 columns">
		<div class="caption align-center">
				<h3 class='small-12'>User Information </h3>
						
				
				<p>
					<table class='small-12'>
					<tr>
						<th>Name:</th><td id='full_name' data-id='{{ $user->id }}' class='edit'>{{ $user->full_name }}</td>
					</tr>
					<tr>
						<th>Nickname:</th><td id='nickname' data-id='{{ $user->id }}' class='edit'>{{ $user->nickname }}</td>
					</tr>
					<tr>
						<th>Email:</th><td id='email' data-id='{{ $user->id }}' class='edit'>{{ $user->email }}</td>
					</tr>
					<tr>
						<th>Date of Birth:</th><td id='date_of_birth' data-id='{{ $user->id }}' class='edit'>{{ Time::parse($user->date_of_birth)->day }}-{{ Time::parse($user->date_of_birth)->month }}-{{ Time::parse($user->date_of_birth)->year }}</td>
					</tr>
					<tr>
						<th>Role:</th><td>@if($user->isSuperAdmin()) Super Admin @else Regular Admin @endif</td>
					</tr>
					<tr>
						<th>Band Member:</th><td>@if($user->band_member)
													<a href='#' class='btn btn-success btn-xs'><i class='icon-ok-sign'></i></a>
												@else
													<a href='#' class='btn btn-danger btn-xs'><i class='icon-remove-sign'></i></a>
												@endif</td>
					</tr>
					<tr>
						<th>Last Login:</th><td>
											@if(!$last_login)
												N/A
											@else
												{{ Time::parse($last_login->created_at)->diffForHumans() }}
											@endif
											</td>
					</tr>
					</table>
				</p>
				<p></p>
			</div>
	</div>

	<div class="small-12 large-8 columns" id="log">
			<div class="caption">
				<h3>User Log</h3>
				<p>
					<table class='small-12'>
						<tr>
							<td colspan='3'>
								<div class='small-6 large-3 columns'>
									<a href='#' data-dropdown='filters' class='button dropdown tiny small-12 columns'>Filters</a><br />

									<ul id="filters" data-dropdown-content class='f-dropdown'>
										<li><a href="{{ URL::current() }}?filter=login#log">Logins</a></li>
										<li><a href="{{ URL::current() }}?filter=logout#log">Logouts</a></li>
										<li><a href="{{ URL::current() }}?filter=failed-login#log">Failed Logins</a></li>
										<li><a href="{{ URL::current() }}?filter=update-account#log">Account Updates</a></li>
										<li><a href="{{ URL::current() }}?filter=request-password-reset#log">Password Reset Requests</a></li>
										<li><a href="{{ URL::current() }}?filter=post-news#log">Posted News Story</a></li>
										<li><a href="{{ URL::current() }}?filter=publish-news#log">Published News Story</a></li>
										<li><a href="{{ URL::current() }}?filter=unpublish-news#log">Unpublished News Story</a></li>
									</ul>
								</div>
								
								<div class='small-6 large-3 align-right columns'>
									<a type="button" href="{{ URL::current() }}#log" class="button tiny alert small-12 columns">Reset Filters</a>
								</div>
							</td>
						</tr>
						<tr>
							<th>Action</th>
							<th>IP Address</th>
							<th>Time</th>
						</tr>
						@if($log_items->count() == 0)
						<tr>
							<td colspan='3'>No items</td>
						</tr>
						@else
							@foreach($log_items as $item)
								@if($item->description != false) 
									<tr>
										<td>{{ $item->description }}</td>
										<td>{{ $item->ip }}</td>
										<td>{{ Time::parse($item->created_at)->diffForHumans() }}</td>
									</tr>
								@endif
							@endforeach
						@endif
					</table>	
					{{ $log_items->links() }}
				</p>
			</div>
	</div>
@stop